### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [marelywoody/cdmx-2018-06-bc-core-am-data-dashboard#11]
Hola @marelywoody y @Dani1592 
He estado revisando el proyecto y tengo algunos comentarios:

1. Buen trabajo de UX, se ve que lo tomaron en serio, espero lo logren realizar lo más fiel posible :clap: 

2. Felicitaciones por esa orientación a testing que tiene :clap: espero lo mantengan durante todo el proyecto, vi que armaran la estructura básica de las funciones tal como lo pedía el test.

3. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

4. En los archivos html se utilizan comillas dobles según el estándar de google.

5. Buena indentación, felicitaciones, un código muy ordenado y limpio es fácil de analizar tanto para codereview como para feedback, sea de quien sea. :clap: :heart: 

6. Que pasó con el deploy a Github Pages? era requisito en el demo del sprint 1.

7. Les recomiendo comenzar a trabajar con la data a profundidad lo antes posible (se encontrarán con toda la lógica para jalar la información y hacer los cálculos) y plasmar tanto visual como funcionalmente lo que tienen pensado para el proyecto.

8. Ojo con los colores de Laboratoria, traten de buscar el manual de normas gráficas de Laboratoria o por último utilizar herramientas de Chrome como colorzilla (es un gotero que saca el código hexadecimal de los colores de una web) para que sea exactamente el color utilizado.

Vamos comiencen luego con a darle forma al datadashboard :muscle: you can do it! :rocket:

**Comment by Dani1592** [comment]
Gracias Alexandra tomaremos en cuenta todos tus comentarios .

**Comment by nerdale** [comment]
Perfecto, daré por cerrado el issue :smile: 
:rocket:
